// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WonderPlace.Models;

namespace WonderPlace.Migrations
{
    [DbContext(typeof(WonderPlaceContext))]
    [Migration("20190601141026_userID_Status")]
    partial class userID_Status
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WonderPlace.Models.Place", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kontynent");

                    b.Property<string>("Kraj");

                    b.Property<string>("Miejsce");

                    b.Property<string>("Opis");

                    b.Property<string>("OwnerID");

                    b.Property<int>("Status");

                    b.Property<string>("Zdjecie");

                    b.HasKey("ID");

                    b.ToTable("Place");
                });
#pragma warning restore 612, 618
        }
    }
}
