// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WonderPlace.Models;

namespace WonderPlace.Migrations
{
    [DbContext(typeof(WonderPlaceContext))]
    partial class WonderPlaceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WonderPlace.Models.Place", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kontynent");

                    b.Property<string>("Kraj");

                    b.Property<string>("Miejsce");

                    b.Property<string>("Opis");

                    b.Property<int>("Status");

                    b.Property<string>("Userid");

                    b.Property<string>("Zdjecie");

                    b.HasKey("ID");

                    b.ToTable("Place");
                });
#pragma warning restore 612, 618
        }
    }
}
